// !function(){return console.log("hi")}()
// void function(){return console.log("hi")}()
// +function(){return console.log("hi")}()
// -function(){return console.log("hi")}()
// ~function(){return console.log("hi")}()
// *function(){return console.log("hi")}()
// ^function(){return console.log("hi")}()
// &function(){return console.log("hi")}()
